### ISSUE TITLE
Unable to connect to database

### ISSUE THREAD

**Issue by em230418** [xoe-labs/dockery-odoo-scaffold#26]
```
Traceback (most recent call last):
  File "/opt/odoo/vendor-9/odoo/cc/odoo/service/wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/vendor-9/odoo/cc/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/vendor-9/odoo/cc/odoo/http.py", line 1326, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/vendor-9/odoo/cc/odoo/http.py", line 1300, in __call__
    return self.app(environ, start_wrapped)
  File "/opt/odoo/.local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/vendor-9/odoo/cc/odoo/http.py", line 1464, in dispatch
    self.setup_db(httprequest)
  File "/opt/odoo/vendor-9/odoo/cc/odoo/http.py", line 1386, in setup_db
    httprequest.session.db = db_monodb(httprequest)
  File "/opt/odoo/vendor-9/odoo/cc/odoo/http.py", line 1549, in db_monodb
    dbs = db_list(True, httprequest)
  File "/opt/odoo/vendor-9/odoo/cc/odoo/http.py", line 1516, in db_list
    dbs = odoo.service.db.list_dbs(force)
  File "/opt/odoo/vendor-9/odoo/cc/odoo/service/db.py", line 340, in list_dbs
    with closing(db.cursor()) as cr:
  File "/opt/odoo/vendor-9/odoo/cc/odoo/sql_db.py", line 638, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/opt/odoo/vendor-9/odoo/cc/odoo/sql_db.py", line 177, in __init__
    self._cnx = pool.borrow(dsn)
  File "/opt/odoo/vendor-9/odoo/cc/odoo/sql_db.py", line 521, in _locked
    return fun(self, *args, **kwargs)
  File "/opt/odoo/vendor-9/odoo/cc/odoo/sql_db.py", line 589, in borrow
    **connection_info)
  File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

To reproduce
```
odooup init test
cd test && make build
make run
```

and open browser

**Comment by em230418** [comment]
Looks like it is not related to `dockery-odoo-scaffold`. Reverted every commit till c5776a9b3498a337873de10972887e744021b839 exclusively and it didn't work.

Yesterday I did same steps and I had working project based on my own `dockery-odoo` image. Comparing logs I payed attention to this line in logs:
```
odoo_1           | 2019-07-09 07:55:16,930 1 INFO ? odoo: database: default@default:default
```
In working project it showed `database: odoo@db:5432`

**Comment by blaggacao** [comment]
@em230418 Usually this means a `make patch` is required to apply the following patches to your local work directory: https://github.com/xoe-labs/dockery-odoo/tree/master/images/v-12.0/spec/base/patches.d

**Comment by em230418** [comment]
Now I do this:
```
odooup init test
cd test
make build
make patch
make run
```
Same behavior, same line in config.

**Comment by blaggacao** [comment]
`make run` should have disappeared... https://github.com/xoe-labs/dockery-odoo-scaffold/blob/97c7d809e430f49d37f6131919e9086694a26eef/Makefile#L152-L193

**Comment by blaggacao** [comment]
I'm trying to replicate...

**Comment by blaggacao** [comment]
> `make run` should have disappeared...

Just saw: I forgot to remove it...

**Comment by blaggacao** [comment]
You might try in different order:
```bash
odooup init test
cd test
make patch
make build
```

patch was prepended because it was a little noisy...

**Comment by blaggacao** [comment]
Ok there is an UX issue with patches, I have to thing how we can solve that...

**Comment by blaggacao** [comment]
If you do
```bash
make build
make patch
make build  # again
```

we should have the desired final state...

**Comment by em230418** [comment]
> we should have the desired final state...

It works! Thanks!

> there is an UX issue with patches, I have to thing how we can solve that...

Yep. I run patch after build, 'cos it tries to get patches from url with registry and fails.

**Comment by blaggacao** [comment]
The UX issue is till something I have to think about, therefore I reopen...
